### ISSUE TITLE
Importing Ogre3D mesh with animations

### ISSUE THREAD

**Issue by blitzcoder** [Vkoslak/torchlight-to-blender#8]
Have you tried importing sample meshes + animations from the ogre3d samples?

So far it only imports skeleton properly but without animations though the xmlconverter reports and lists all animations when generating the xml skeleton file.

I'm using Ogre 1.7.2 command line tools.

**Comment by sercero** [comment]
@blitzcoder have you tried [blender2ogre](https://github.com/OGRECave/blender2ogre)?

Despite its name it also does ogre2blender.

**Comment by blitzcoder** [comment]
Oh hey @sercero. Thanks, will try that as well.

**Comment by RobJames-Texas** [comment]
I'm assuming you are trying to import models from Torchlight or Torchlight 2.  The current implementation only imports whatever animations are in the skeleton file which by default is only the BIND animation since the Torchlight series stores animations in separate files.   I've started working on being able to import individual animations, but I have not finished it yet.

**Comment by blitzcoder** [comment]
Hey @RobJames-Texas actually not Torchlight, but the Ogre SDK models under `Samples/Media` which has all the animations in their corresponding skeleton file.

Comparing with blender2ogre, I found this addon imports all the skeletons properly so far, but apparently w/o the animations.

**Comment by RobJames-Texas** [comment]
Ok,  thanks for clarifying.  I will take a look when I get some time.

**Comment by RobJames-Texas** [comment]
It appears the animation import only works with 2.79.  For 2.8 I need to change an operator,  but then it would break 2.79 support.   Many in the torchlight modding community still use 2.79 because they are familiar with it.  
I'll try to add a conditional to handle both.  I will eventually stop supporting 2.79.

**Comment by blitzcoder** [comment]
Great, jaiqua animations are now importing properly. 👍 

Testing out more meshes also works but somehow not lookin good with the animations.. example with sinbad mesh here: https://github.com/dsaltares/iberogre/tree/master/ogre/animacion/media

Somehow the bone rotation animation are half-body..

![screen](https://user-images.githubusercontent.com/57479219/194805474-e6c3ebd3-4c27-43aa-b7ea-d287045cd351.jpg)

or all bones are twisted.. this one below on another model with Mesh Serializer 1.30. I guess it doesn't make any difference if you have the mesh.xml files..?

![screen2](https://user-images.githubusercontent.com/57479219/194805579-b1aa46ac-4673-469c-9884-0eaf6c6c6a68.png)

> It appears the animation import only works with 2.79

Thanks for the info, will also try with Blender 2.79 and both previous and latest release.
